### PR TITLE
feat: add support for Grafana Loki

### PR DESCRIPTION
**Pull request by charsleysa**
- adds support for Grafana Loki that is compatible with Grafana Cloud
- fixes erasearch

### CODE REVIEW

**Comment by jeromegn** [comment]
This looks fine!

I'm curious as to why EraSearch and Loki require JSON logs? I mean, shouldn't this log shipper wrap logs in JSON before sending them instead of checking if logs are already JSON-formatted?

**Comment by charsleysa** [comment]
Not sure about EraSearch but with Loki the message is already wrapped in JSON with all the information that comes from fly.

The issue is that if your app outputs json logs then your json is treated as a string and wrapped again making it difficult to use.

By checking to see if the message is json, we can parse it and merge it into the main json object to be sent.

This allows functionality like the app being able to set the log level (otherwise all app logs would be "info" level).

Here's an example of the final result seen in Grafana. The `fly`, `host`, `event`, and `log` properties come from fly while other properties come from our app after the log message was processed as json and merged into the main object.
```
{"event":{"provider":"app"},"fly":{"app":{"instance":"dad014e6","name":"mymahi-api-staging"},"region":"syd"},"host":"2958","hostname":"dad014e6","level":"info","log":{"level":"info"},"msg":"request completed","pid":527,"res":{"statusCode":200},"responseTime":4.244934000074863,"time":"2022-02-25T19:50:56.432Z","traceId":"986133f07e9e0e2f2ad8db980fa35cb7"}
```

**Comment by Speenah** [comment]
I was planning to look into adding Loki as well then saw this PR was up! 

One thing I noticed though is that [Vector docs](https://vector.dev/docs/reference/configuration/sinks/loki/#out_of_order_action) say that Loki isn't able to accept out of order writes and will drop events off out of order by default, but [Grafana docs](https://grafana.com/docs/loki/latest/configuration/#accept-out-of-order-writes) say Loki is able to accept out of order writes. Have you noticed any issues with this?

**Comment by charsleysa** [comment]
@Speenah the default by Vector is to drop out of order logs. I haven't seen any messages about out of order logs being dropped so I don't think it's much of an issue but your experience may differ. Our production setup is dual node running in separate regions for High Availability.

**Pull request merged**
