### PR TITLE
Add Honeybadger sink

### PR DESCRIPTION
**Pull request by stympy**
This adds support for Honeybadger's upcoming [structured logging feature](https://docs.honeybadger.io/guides/insights/), which is currently in preview.

### CODE REVIEW

**Comment by stympy** [comment]
This is tested and working, using a [docker image](https://hub.docker.com/r/honeybadgerindustries/fly-log-shipper) built from the forked repo.

Screenshot of the Honeybadger UI showing querying of the logs shipped by Vector from a sample app:
Honeybadger Insights

**Comment by stympy** [comment]
@draper7 could you take a look at this? We have mutual customers who would like to use it. :)

**Review by draper7 — APPROVED** [review]

**Comment by draper7** [comment]
@stympy thanks, I'll create a release shortly.

**Comment by stympy** [comment]
Thanks!

**Comment by draper7** [comment]
Pushed to latest, ghcr.io/superfly/fly-log-shipper:latest

**Pull request merged**
